### ISSUE TITLE
"\in" in Strings

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#150]
Originally reported by: **Markus Pfeiffer (Bitbucket: [markusp](http://bitbucket.org/markusp), GitHub: [markusp](http://github.com/markusp))**

---

I recently added some code to GAP to detect escape sequences that are probably not as they were intended to be. In Semigroups there are multiple instances of

```
Error("Semigroups: \in: usage,\n"
```

in strings "\in", GAP ignores the backslash when reading it, so the resulting displayed error message would be

```
Error: Semigroups: in: usage,
```

so you could leave the backslash out anyway. If you want to display a backslash you have to use a double backslash. From GAP 4.9 strings that contain a backslash followed by a letter that is not part of an escape sequence will produce a warning.

---
- Bitbucket: https://bitbucket.org/james-d-mitchell/semigroups/issue/151

**Comment by james-d-mitchell** [comment]
This is resolved, I'm going to close it.

**Comment by wilfwilson** [comment]
This issue is not resolved.

For some reason this issue has number #150, even though it has [number 151 on Bitbucket](https://bitbucket.org/james-d-mitchell/semigroups/issues/151). [The original issue 150 on Bitbucket](https://bitbucket.org/james-d-mitchell/semigroups/issues/150) is what my above-mentioned commits refer to.

Several of the relevant error messages do use `\\in`, whilst some others only have a single backslash, `\in`. I presume we want the former? In this case, we need to update gaplint (especially since we want to integrate it into the Travis testing - Issue #171. I've been playing around with this). This is because gaplint is linting the method `\in`, and so it expects its Error messages to include precisely that string. But it needs to both look for `\\in`, and report `\\in` as the desired string when it is not found.

**Comment by wilfwilson** [comment]
I detailed the gaplint problem in [Issue 10 on Bitbucket](https://bitbucket.org/james-d-mitchell/gaplint/issues/10). I'm going to go ahead sort this out so that everything in the Semigroups package should be `\\in`, and gaplint handles it properly.

**Comment by wilfwilson** [comment]
Sorry you're quite right, this is resolved - I confused myself for various reasons included the incorrectly associated commits which appear in this thread. I will deal with the gaplint problem separately (since the correct `\\in` strings currently give an error).

**Comment by wilfwilson** [comment]
@james-d-mitchell Sorry for the storm of activity on this issue, especially on a Saturday morning (I just fancy doing some work).

Whilst the strings for `\in`, `\<`, and `\.` are indeed correct in `unstable-3.0`, I found some `\^` and `\*` Error strings that needed changing.

Also: the strings are still the old way in `stable-2.8`. Are you happy to leave them as they are? As things stand, when GAP 4.9 is released, people running Semigroups 2.8.0 will encounter the warnings that Markus mentioned in the original issue.

**Comment by james-d-mitchell** [comment]
I don't want to release another version of Semigroups 2.8, so yes I'm happy with this.

**Comment by wilfwilson** [comment]
I'm happy with that too. My commit 788f252 resolves the remaining cases in `unstable-3.0`, so I'll close this now.

**Comment by wilfwilson** [comment]
Just to note, gaplint now behaves correctly with regard to this issue.
