### ISSUE TITLE
Bug in IsGreensDLeq for an inverse semigroup

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#237]
Whilst writing code coverage for `attrinv.gi`, I kept getting weird answers. It's taken me over an hour to realise that it's bug, and to track it down as far as the following:
```
gap> T := Semigroup([
>  Transformation([1, 2, 6, 4, 5, 6]),
>  Transformation([1, 2, 3, 4, 6, 6]),
>  Transformation([1, 2, 3, 6, 5, 6]),
>  Transformation([1, 6, 6, 4, 5, 6]),
>  Transformation([1, 6, 3, 4, 6, 6]),
>  Transformation([1, 6, 3, 6, 5, 6]),
>  Transformation([6, 2, 3, 6, 5, 6]),
>  Transformation([6, 2, 6, 4, 5, 6]),
>  Transformation([6, 2, 3, 4, 6, 6])]);;
gap> x := Transformation([1, 6, 3, 6, 6, 6]);;
gap> y := Transformation([6, 6, 3, 6, 6, 6]);;
gap> IsIdempotent(x) and IsIdempotent(y) and x in T and y in T;
true

gap> I := IdempotentGeneratedSubsemigroup(T);;
gap> IsGreensDLeq(I)(x, y);
true

gap> T := Semigroup(T);;
gap> I := IdempotentGeneratedSubsemigroup(T);;
gap> IsInverseSemigroup(I);
true
gap> IsGreensDLeq(I)(x, y);
false
```
The correct answer is that `D_x > D_y`, so it should be returning `true` here. But somehow `IsGreensDLeq` is going wrong when `T` knows that it is inverse.

**Comment by james-d-mitchell** [comment]
It looks like the method for `PartialOrderOfDClasses` for a regular acting semigroup is not functioning as intended. Good catch.

**Comment by james-d-mitchell** [comment]
Or maybe that there should be a method for `IsGreensDLeq` for regular acting semigroups

**Comment by james-d-mitchell** [comment]
There is no easy fix for this issue, I think I'll have to make some bigger changes

**Comment by james-d-mitchell** [comment]
I fixed this in ec8336f6b9, will wait for travis to complete before merging your PR.

**Comment by wilfwilson** [comment]
I'll rebase my stuff on top of this just to make double sure.

**Comment by wilfwilson** [comment]
The failing test in my PR (which prompted this issue) is still failing. The test asks for `PrimitiveIdempotents(T)`, where `T` is the semigroup defined at the start of this issue. There should be 5; currently 7 are being returned (and 8 were being returned before your commits today).

```
gap> T := Semigroup([
>  Transformation([1, 2, 6, 4, 5, 6]),
>  Transformation([1, 2, 3, 4, 6, 6]),
>  Transformation([1, 2, 3, 6, 5, 6]),
>  Transformation([1, 6, 6, 4, 5, 6]),
>  Transformation([1, 6, 3, 4, 6, 6]),
>  Transformation([1, 6, 3, 6, 5, 6]),
>  Transformation([6, 2, 3, 6, 5, 6]),
>  Transformation([6, 2, 6, 4, 5, 6]),
>  Transformation([6, 2, 3, 4, 6, 6])]);;
gap> i := PrimitiveIdempotents(T);
[ Transformation( [ 1, 6, 6, 6, 6, 6 ] ),
  Transformation( [ 6, 2, 3, 6, 6, 6 ] ),
  Transformation( [ 6, 2, 6, 6, 6, 6 ] ),
  Transformation( [ 6, 6, 3, 4, 6, 6 ] ),
  Transformation( [ 6, 6, 3, 6, 6, 6 ] ),
  Transformation( [ 6, 6, 6, 4, 6, 6 ] ),
  Transformation( [ 6, 6, 6, 6, 5, 6 ] ) ]
gap> i[2] * i[3] = i[3];
true
gap> i[4] * i[5] = i[5];
true
```
So `i[2]` and `i[4]` are the non-primitive ones.

**Comment by james-d-mitchell** [comment]
This is a separate issue. Which is relatively easy to fix. More details to follow.

**Comment by wilfwilson** [comment]
Glad to hear it.

**Comment by wilfwilson** [comment]
Can you reproduce this bug @james-d-mitchell ?

```
gap> S := Semigroup([
>  Transformation([1, 2, 6, 4, 5, 6]),
>  Transformation([1, 2, 3, 4, 6, 6]),
>  Transformation([1, 2, 3, 6, 5, 6]),
>  Transformation([1, 6, 6, 4, 5, 6]),
>  Transformation([1, 6, 3, 4, 6, 6]),
>  Transformation([1, 6, 3, 6, 5, 6]),
>  Transformation([6, 2, 3, 6, 5, 6]),
>  Transformation([6, 2, 6, 4, 5, 6]),
>  Transformation([6, 2, 3, 4, 6, 6])]);; # the semigroup <T> from earlier
gap> z := Transformation([6, 6, 3, 4, 6, 6]);;
gap> z_a := Transformation([6, 6, 3, 6, 6, 6]);;
gap> z_b := Transformation([6, 6, 6, 4, 6, 6]);;
gap> elts := ShallowCopy(Elements(S));;
gap> Sort(elts, IsGreensDLeq(S));

# <elts> should now be sorted so that
# D_x > D_y => x appears earlier than y in <elts>
# But I can find elements which do not agree with this:

gap> Position(elts, z);
22
gap> Position(elts, z_a);
17
gap> Position(elts, z_b);
20
gap> IsGreensDLeq(S)(z, z_a) and IsGreensDLeq(S)(z, z_b);
true
```
Here `IsGreensDLeq` is giving the correct answer: `D_z > D_z_a` and `D_z > D_z_b` since:
```
gap> z * z_a = z_a;
true
gap> z * z_b = z_b;
true
```
Perhaps the bug is in `Sort`?

**Comment by wilfwilson** [comment]
I think we might not be using `Sort` correctly. I'm investigating.

**Comment by wilfwilson** [comment]
The function given to `Sort`, `Sortex` should be a *strict* ordering, not a less-than-or-equal ordering. So:

1: original, bad answer
```
gap> S := Semigroup(S);;
gap> elts := ShallowCopy(Elements(S));;
gap> Sort(elts, IsGreensDLeq(S));
gap> Position(elts, z); Position(elts, z_a); Position(elts, z_b);
22
17
20
```

2: should give the same result since the code is essentially the same, and it does:
```
gap> S := Semigroup(S);;
gap> elts := ShallowCopy(Elements(S));;
gap> func := function(x, y)
  return IsGreensDLeq(S)(x, y);
end;;
gap> Sort(elts, func);
gap> Position(elts, z); Position(elts, z_a); Position(elts, z_b);
22
17
20
```

3: make sure ordering is not "(greater/less) than or equal"
```
gap> S := Semigroup(S);;
gap> elts := ShallowCopy(Elements(S));;
gap> func := function(x, y)
  if x = y then
    return false;
  fi;
  return IsGreensDLeq(S)(x, y);
end;;
gap> Sort(elts, func);
gap> Position(elts, z); Position(elts, z_a); Position(elts, z_b);
22
24
26
```
Good answer.

**Comment by wilfwilson** [comment]
This resolves the bug posted in [my previous comment](https://github.com/gap-packages/Semigroups/issues/237#issuecomment-266719645).

**Comment by wilfwilson** [comment]
This is resolved by commit dcbb037
