### ISSUE TITLE
Semigroups does not compile with current master branch

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-packages/Semigroups#497]
Semigroups 3.0.16 fails to build with master branch on June 14: 
````
Running 'make' 
Making all in src/libsemigroups
make[1]: Entering directory '/mnt/work/ghorvath/gap/pkg/semigroups-3.0.16/src/libsemigroups'
  CXX      src/libsemigroups_la-blocks.lo
  CXX      src/libsemigroups_la-cong.lo
  CXX      src/libsemigroups_la-elements.lo
  CXX      src/libsemigroups_la-semigroups.lo
  CXX      src/libsemigroups_la-rws.lo
  CXX      src/libsemigroups_la-rwse.lo
  CXX      src/libsemigroups_la-uf.lo
  CXXLD    libsemigroups.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/mnt/work/ghorvath/gap/pkg/semigroups-3.0.16/src/libsemigroups'
make[1]: Entering directory '/mnt/work/ghorvath/gap/pkg/semigroups-3.0.16'
  CXX      src/semigroups_la-pkg.lo
src/pkg.cc:410:6: error: invalid conversion from ‘GVarFilt {aka long unsigned int** (*)()}’ to ‘UInt** (*)(Obj, Obj) {aka long unsigned int** (*)(long unsigned int**, long unsigned int**)}’ [-fpermissive]
(GVarFilt) IsBipartHandler,
^~~~~~~~~~~~~~~~~~~~~~~~~~
src/pkg.cc:416:6: error: invalid conversion from ‘GVarFilt {aka long unsigned int** (*)()}’ to ‘UInt** (*)(Obj, Obj) {aka long unsigned int** (*)(long unsigned int**, long unsigned int**)}’ [-fpermissive]
(GVarFilt) IsBlocksHandler,
^~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:600: recipe for target 'src/semigroups_la-pkg.lo' failed
make[1]: *** [src/semigroups_la-pkg.lo] Error 1
make[1]: Leaving directory '/mnt/work/ghorvath/gap/pkg/semigroups-3.0.16'
Makefile:665: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

WARNING: Failed to build semigroups-3.0.16
````

I am using debian stretch, my gcc version is the following: 
````
ghorvath@Toshiba:~/work/gap/pkg/log$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
````

As far as I remember, the previous version compiled fine. Semigroups 3.0.15 definitely compiles ok with the stable 4.9.1 branch.

**Comment by james-d-mitchell** [comment]
Thanks for the issue @hungaborhorvath, I was already aware of this. Several recent changes in the master branch of GAP have broken Semigroups, and I decided not to fix them until `master` stabilises a bit more. The fix for this issue is not compatible with `stable-4.9`, and I didn't yet figure out how to fix for both branches simultaneously.

**Comment by james-d-mitchell** [comment]
PS: I suggest using Semigroups against `stable-4.9` instead for the time being.

**Comment by james-d-mitchell** [comment]
Or if that's not an option, then I can provide a patch.

**Comment by hungaborhorvath** [comment]
It is fine, I can use the stable version, I just wanted to make sure that you are aware.

(Offtopic: Actually, for me it is a bigger pain that you require gcc >= 5.0, and my production laptop is still based on debian jessie, which uses only gcc v4.9. So on that laptop I cannot ever use the stable version, only an older one, like 4.8.10, or something, which misses out on a lot of other tweaks from GP. But whatever, I really should update this machine.... Right now, if I need to use it, I use another laptop, which is slower, but I already installed debian stretch on it.)

**Comment by james-d-mitchell** [comment]
I can imagine it is a pain to have to use gcc >=5.0, but this is because there are numerous bugs in gcc 4.8/4.9 relating to C++11, one of which I could not find a workaround for, which means that while you can compile Semigroups with GCC 4.8 and 4.9 it fails with an exception at run time.

**Comment by james-d-mitchell** [comment]
This was resolved by PR #499.

**Comment by alex-konovalov** [comment]
Thank you for fixing this - a new release would be nice, otherwise it still fails e.g. in https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/404679392

**Comment by alex-konovalov** [comment]
@james-d-mitchell Ping?

**Comment by james-d-mitchell** [comment]
Hmm, so this was fixed, but then the `MatrixObj` stuff was merged into `master` and now Semigroups doesn't work any more. I'm going to reopen this issue. It will be difficult to resolve this issue without a major refactoring of some parts of Semigroups, unfortunately.

**Comment by james-d-mitchell** [comment]
Hm, or rather Semigroups compiles fine, but the tests don't run with GAP `master`.

**Comment by alex-konovalov** [comment]
Yes, that is also now reported at https://github.com/gap-system/gap/issues/2737. I will write there a couple of proposals how to handle this.
